---
# supported frameworks: mocha|jest|jasmine
framework: jest

preRun:
  # set of commands to run before running the tests like `yarn install`, `yarn build`
  command:
    - wget -qO- https://download.rethinkdb.com/repository/raw/pubkey.gpg | gpg --dearmor -o /usr/share/keyrings/rethinkdb-archive-keyrings.gpg
    - echo "deb [signed-by=/usr/share/keyrings/rethinkdb-archive-keyrings.gpg] https://download.rethinkdb.com/repository/ubuntu-$(lsb_release -cs) $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/rethinkdb.list
    - apt-get update
    - apt-get install rethinkdb
    - rethinkdb --bind all &
    - cd /home/nucleus/repo
    - yarn
    - yarn db:reset


postMerge:
  pattern:
    - "**/*.test.js"
  # strategy for trigerring builds for post-merge
  strategy:
    threshold: 1
    name: after_n_commits

preMerge:
  pattern:
    - "**/*.test.js"

config: jest.config.js

# configure whether to smartSelect test-cases. Default true
smartRun: true

# number of containers in which the tests must be splitted into for execution
parallelism: 1

# version of tas file intended to be used in order to issue warnings for deprecation or breaking changes
version: 1.0.0
